### ISSUE TITLE
pipe Auth ID to wush ssh

### ISSUE THREAD

**Issue by amigthea** [coder/wush#26]
how can I directly pipe the auth id to wush commands without explicitly insert it by user input?

**Comment by gdmn** [comment]
````
TEMP_DIR="$(mktemp -d)"
mkfifo $TEMP_DIR/auth
wush serve | while read l; do
    echo "$l" >> $TEMP_DIR/auth
done &
AUTH="$(cat $TEMP_DIR/auth)"
echo "auth: $AUTH"
wait
```

**Comment by coadler** [comment]
Going to close, @gdmn's option seems to be the best here. We won't be able to accept the auth key via stdin because we'll need to attach that to the tty for input.
