### ISSUE TITLE
problem with stdout

### ISSUE THREAD

**Issue by amigthea** [coder/wush#27]
I'm prefacing this by saying that the problem is likely on my low linux skills.

this command prints the authid on terminal (with other stderr logs)
`wush host | cat`

but this is not printing the expected encoded output
`wush host | base64`

what I'm doing wrong?
thank you for the patience and keep it up with this awesome project!

**Comment by coadler** [comment]
It's most likely that `base64` is waiting for an EOF from `wush host` since we never close stdout. FWIW, the auth key is already base58 encoded, so base64ing it unnecessary.

**Comment by amigthea** [comment]
> It's most likely that `base64` is waiting for an EOF from `wush host` since we never close stdout.

that's what I thought and I was able to work around that with xargs, eg:
`
wush host | xargs -I {} sh -c 'echo {}'`

can I ask you if there's a more clean way, maybe with `tee`?

anyway thank you for the heads-up, much appreciated

**Comment by amigthea** [comment]
solved it with
`wush host | tee >(  my command ) > /dev/null`
thank you <3
