### ISSUE TITLE
`wush ssh` freezes terminal if server goes down

### ISSUE THREAD

**Issue by sharkymark** [coder/wush#33]
In my scenario, it is a Coder remote development environment running `wush serve`

If I connect to it with `wush ssh` and then stop the workspace, the local terminal doesn't end the ssh session like normal ssh does, and instead locks that terminal forcing a close of the terminal window to resolve.

**Comment by coadler** [comment]
Good find, I can probably fix this with either SSH keep-alives or adjusting some socket options.
