### ISSUE TITLE
wush.dev terminal sharing

### ISSUE THREAD

**Issue by ammario** [coder/wush#40]
At the moment @coadler is working a version of wush.dev that can host terminals to a local `wush serve` instead making it even easier to share terminals with everyone. The UX would be roughly:

```
$ wush serve
Auth key:
*  Q29uZmlndXJlIGl0IHdpdGggYSByYW5kb20gc2Vj
OR share this:
*  https://wush.dev/#Q29uZmlndXJlIGl0IHdpdGggYSByYW5kb20gc2Vj
```

Alongside the change we will try to make the terminal collaborative, so the web term could monitor whats happening in the real term and vice versa. It wills serve as more secure, faster alternative to tmate.

**Comment by ammario** [comment]
To comment more on the security, we plan to store the encryption key in the URL fragment so it's never sent to a Coder server. The web client will then initiate the connection with Tailscale using their DERP over WebSocket directly.

There will be no sign ups. Transfers will continue being totally anonymous.

**Comment by coadler** [comment]
Unpinning this now, https://wush.dev is shipped, but we decided against terminal sharing. It does support browser shells, but spawns a new TTY for each connection.
