### ISSUE TITLE
Custom Derp Server

### ISSUE THREAD

**Issue by shyim** [coder/wush#43]
Thanks for the project!

I am hosting my own derp server to increase the performance using https://tailscale.com/kb/1118/custom-derp-servers

Would it be possible to use that instead of official servers?

**Comment by coadler** [comment]
Yeah! See: https://coder.com/docs/reference/cli/server#--derp-config-url or https://coder.com/docs/reference/cli/server#--derp-config-url

**Comment by coadler** [comment]
Great idea, I'll add an option for that :+1:
